//use collection name
use program_education;

db.languages.drop();

var languageData = [
{
  id: 1,
  language: "C",
  author: "Dennis Ritchie",
  description: "General-purpose low level language that a lot of current languages are derivatives of, created for UNIX systems",
  year: "1972",
  usedBy: "UNIX, embedded systems",
  usedFor: "Cross-platform programming, system programming, UNIX programming",
  exampleCode: "#include<stdio.h>\n main()\n   {\n      printf('Hello World');\n\n  }",
  pros: ["Small clean language", "Very powerful", "Can be used in C++ programs"],
  cons: ["Difficult to learn", "Code can get messy quickly", "Needs to be compiled"],
  popularity: [
    {"2004": 8.4},
    {"2005": 8.2},
    {"2006": 7.6},
    {"2007": 7.4},
    {"2008": 7.6},
    {"2009": 9.6},
    {"2010": 10.8},
    {"2011": 11.7},
    {"2012": 8.2},
    {"2013": 7.6},
    {"2014": 7.6},
    {"2015": 7.4},
    {"2016": 7.0},
    {"2017": 6.1}
  ],
  documentation: [{"C Docs": "http://devdocs.io/c/"}],
  links: [{"C Tutorial": "https://www.cprogramming.com/tutorial/c-tutorial.html"}],
  icon: "https://seeklogo.com/images/C/c-programming-language-logo-9B32D017B1-seeklogo.com.png"
},
{
  id: 2,
  language: "Objective C",
  author: "Brad Cox and Tom Love",
  description: "Objective-C is a general-purpose, object-oriented programming language that adds Smalltalk-style messaging to the C programming language. It was the main programming language used by Apple for the OS X and iOS operating systems, and their respective application programming interfaces (APIs) Cocoa and Cocoa Touch prior to the introduction of Swift.",
  year: "1983",
  usedBy: "Apple",
  usedFor: "Apple Programming",
  exampleCode: "// First program example \n #import <Foundation/Foundation.h> \n \n int main (int argc, const char * argv[]) \n  { \n           NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init]; \n           NSLog (@'Hello, World!');\n           [pool drain];\n           return 0;\n  }",
  pros: ["Object Oriented Language", "Objective-C incorporates C so you get all the benefits of C when working within Objective-C", "You can program for Mac and iOS" ],
  cons: ["There will be aspects of learning C at the same time.", "Big learning curve", ],
  popularity: [
    {"2004": 0.0},
    {"2005": 0.0},
    {"2006": 0.0},
    {"2007": 0.0},
    {"2008": 0.0},
    {"2009": 0.0},
    {"2010": 0.9},
    {"2011": 2.8},
    {"2012": 4.5},
    {"2013": 5.8},
    {"2014": 5.9},
    {"2015": 5.0},
    {"2016": 4.4},
    {"2017": 3.5}
],
  documentation: [{"Objective C Docs": "https://developer.apple.com/documentation/objectivec?language=objc"}],
  links: [{"Useful Code Snippets": "https://gist.github.com/imagin4ry/7024758"}, {"Additional Information": "https://www.tutorialspoint.com/objective_c/objective_c_useful_resources.htm"}],
  icon: "https://achievement-images.teamtreehouse.com/iOS_Objective_C.png"
},
{
  id: 3,
  language: "C++",
  author: "Bjarne Stroustrup",
  description: "C++ is a general-purpose programming language. It has imperative, object-oriented and generic programming features, while also providing facilities for low-level memory manipulation.",
  year: "1983",
  usedBy: "Adobe System, Mozilla, Google",
  usedFor: "Google Chromium, Adobe Illustrator",
  exampleCode: "#include <iostream>\n\n int main()\n {\n    std::cout << 'Hello World!';\n }",
  pros: ["Combines the low level power of C with several layers of abstraction."],
  cons: ["C++ is extremely huge and its various features interact in horribly complex ways."],
  popularity: [
    {"2004": 13.4},
    {"2005": 12.5},
    {"2006": 11.2},
    {"2007": 10.7},
    {"2008": 10.6},
    {"2009": 10.8},
    {"2010": 9.7},
    {"2011": 9.0},
    {"2012": 8.8},
    {"2013": 8.6},
    {"2014": 7.8},
    {"2015": 7.5},
    {"2016": 6.9},
    {"2017": 6.8}
    ],
  documentation: [{"C++ Docs": "https://isocpp.org/"}],
  links: [{"Wikipage": "https://en.wikipedia.org/wiki/C%2B%2B"}],
  icon: "http://www.freeiconspng.com/uploads/c--logo-icon-0.png"
},
{
  id: 4,
  language: "Visual Basic",
  author: "Microsoft",
  description: "Visual Basic is a third-generation event-driven programming language and integrated development environment (IDE) for its Component Object Model (COM) programming mode",
  year: "1991",
  usedBy: "Microsoft",
  usedFor: "Microsoft intended Visual Basic to be relatively eary to learn and use. Visual Basic was derived from BASIC, a user friendly programming language designed for beginners, and it enables rapid application development (RAD) of graphical user interface (GUI) applications",
  exampleCode: " Console.WriteLine ('Hello World using Visual Basic!') ",
  pros: ["easy to use and learn", "widespread applicability"],
  cons: ["memory constraints"],
  popularity: [
    {"2004": 7.4},
    {"2005": 6.4},
    {"2006": 5.5},
    {"2007": 4.8},
    {"2008": 5.0},
    {"2009": 4.9},
    {"2010": 4.5},
    {"2011": 4.0},
    {"2012": 3.4},
    {"2013": 2.8},
    {"2014": 2.3},
    {"2015": 1.9},
    {"2016": 1.6},
    {"2017": 1.3}
  ],
  documentation: [{"Visual Basic Docs": "https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference"}],
  links: [{"YouTube Tutorial": "https://www.youtube.com/watch?v=3FkWddODLno"}],
  icon: "http://www.diginetinfosystems.com/content/newimg/vb6.png"
},
{
  id: 5,
  language: "Python",
  author: "Guido van Rossum (DropBox)",
  description: "Python is a widely used high-level programming language for general-purpose programming",
  year: "1991",
  usedBy: "NASA, Google, Wikipedia, Yahoo",
  usedFor: "Python can serve as a scripting language for web applications and with web frameworks support developers in the design and maintenance of complex applications.",
  exampleCode: "print('Hello World')",
  pros: ["says Pierre Carbonnelle:This has benefits to you and to others.It helps you think more clearly when writing programs, and it helps the others who will maintain or enhance your program.In both cases, it requires less effort to write a Python program than to write one in another language like C++ or Java. "],
  cons: ["Because it is an interpreted language, it is often many times slower than compiled languages."],
  popularity: [
    {"2004": 2.4},
    {"2005": 3.3},
    {"2006": 3.8},
    {"2007": 4.7},
    {"2008": 5.3},
    {"2009": 5.8},
    {"2010": 6.0},
    {"2011": 7.0},
    {"2012": 7.7},
    {"2013": 9.3},
    {"2014": 10.0},
    {"2015": 11.4},
    {"2016": 13.8},
    {"2017": 17.0}
    ],
  documentation: [{"Python Docs": "https://www.python.org/"}],
  links: [{"Wikipage": "https://en.wikipedia.org/wiki/Python_(programming_language)#Uses"}],
  icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/2000px-Python.svg.png"
},
{
  id: 6,
  language: "Ruby",
  author: "Yukihiro 'Matz' Matsumoto",
  description: "Ruby is a dynamic, reflective, object-oriented, general-purpose programming language. According to its creator, Ruby was influenced by Perl, Smalltalk, Eiffel, Ada, and Lisp.[11] It supports multiple programming paradigms, including functional, object-oriented, and imperative. It also has a dynamic type system and automatic memory management.",
  year: "1993",
  usedBy: "FreeAgent",
  usedFor: "Web applications",
  exampleCode: "puts 'hello world' ",
  pros: ["easy to use and learn", "object-oriented"],
  cons: ["not as efficent as other languages"],
  popularity: [
    {"2004": null},
    {"2005": 1.0},
    {"2006": 2.2},
    {"2007": 2.8},
    {"2008": 2.5},
    {"2009": 2.4},
    {"2010": 2.2},
    {"2011": 2.4},
    {"2012": 2.5},
    {"2013": 2.5},
    {"2014": 2.4},
    {"2015": 2.3},
    {"2016": 2.1},
    {"2017": 1.6}
  ],
  documentation: [{"Ruby Docs": "https://ruby-doc.org/core-2.4.1/"}],
  links: [{"Ruby Tutorial": "http://rubylearning.com/satishtalim/tutorial.html"}],
  icon: "https://upload.wikimedia.org/wikipedia/commons/7/73/Ruby_logo.svg"
},
{
  id: 7,
  language: "PHP",
  author: "Rasmus Ledorf",
  description: "PHP is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded into HTML",
  year: "1995",
  usedBy: "Facebook, Wikipedia, Digg and Wordpress",
  usedFor: "Creating/Maintaining dynamic webpages and server-side development",
  exampleCode: "echo 'hello world'",
  pros: ["Open source (free to use)", "Relatively efficent", "Works on most platforms."],
  cons: ["Security due to being open-source anyone can view the source code and find weaknesses", "Not suitable for larger applications due to lack of modularity."],
  popularity: [
    {"2004": 17.4},
    {"2005": 17.7},
    {"2006": 17.8},
    {"2007": 17.9},
    {"2008": 17.6},
    {"2009": 16.8},
    {"2010": 15.4},
    {"2011": 14.5},
    {"2012": 13.5},
    {"2013": 12.6},
    {"2014": 11.5},
    {"2015": 10.6},
    {"2016": 9.7},
    {"2017": 8.7}
  ],
  documentation: [{"PHP Docs": "http://php.net/docs.php"}],
  links: [{"PHP Tutorials": "http://www.homeandlearn.co.uk/php/php.html"}],
  icon: "https://dt-cdn.net/assets/images/gfx/icons/tech/php-fbd1629392.svg"
},
{
  id: 8,
  language: "Java",
  author: "James Gosling",
  description: "Java is a general-purpose computer programming language that is concurrent, class-based, object-oriented,[14] and specifically designed to have as few implementation dependencies as possible. It is intended to let application developers 'write once, run anywhere' (WORA), meaning that compiled Java code can run on all platforms that support Java without the need for recompilation. Java is one of the most popular programming language used worldwide. The Java language is a key pillar in Android, an open source mobile operating system.",
  year: "1995",
  usedBy: "Android OS/apps",
  usedFor: "Network Programming ,web application development, software development, Graphical User Interface development",
  exampleCode: "public class HelloWorld {\n\n         public static void main(String[] args) {\n            // Prints 'Hello, World' to the terminal window.\n             System.out.println('Hello, World');\n         }\n     }",
  pros: ["Currently most used language", "Used for Android app development", "Object Oriented", "Comprehensive Documentation"],
  cons: ["Can't use multiple inheritence" ,"Though garbage collection is automatic, it’s sometimes poorly or inefficiently done in Java." ,"Primitive types don't inherit from Object."],
  popularity: [
    {"2004": 26.1},
    {"2005": 26.9},
    {"2006": 26.6},
    {"2007": 27.4},
    {"2008": 26.1},
    {"2009": 25.2},
    {"2010": 26.4},
    {"2011": 25.6},
    {"2012": 25.3},
    {"2013": 24.5},
    {"2014": 24.1},
    {"2015": 24.1},
    {"2016": 22.9},
    {"2017": 22.4}
  ],
  documentation: [{"Java Docs": "http://docs.oracle.com/javase/8/docs/"}, {"Java APIs": "http://docs.oracle.com/javase/8/docs/api/"}],
  links: [{"Java Basic Tutorial": "https://www.tutorialspoint.com/java/java_basic_syntax.htm"}, {"Java Tutorial": "https://docs.oracle.com/javase/tutorial/java/nutsandbolts/index.html"}],
  icon: "https://logos-download.com/wp-content/uploads/2016/10/Java_logo_icon.png"
},
{
  id: 9,
  language: "JavaScript",
  author: "Brendan Eich Mozilla",
  description: "JavaScriptis a high-level, dynamic, weakly typed, object-based, multi-paradigm, and interpreted programming language",
  year: "1995",
  usedBy: "Google, Twitter, FaceBook",
  usedFor: "Uber, Slack",
  exampleCode: " console.log('Hello World')",
  pros: ["Speed, Simplicity, Versatility, Server load"],
  cons: ["Security, Reliance on End User."],
  popularity: [
    {2004: 7.1},
    {2005: 7.7},
    {2006: 7.9},
    {2007: 7.6},
    {2008: 7.3},
    {2009: 7.0},
    {2010: 6.2},
    {2011: 6.7},
    {2012: 6.5},
    {2013: 6.9},
    {2014: 7.1},
    {2015: 7.2},
    {2016: 7.7},
    {2017: 8.0},
  ],
  documentation: [{"JS Docs":"https://developer.mozilla.org/en-US/docs/Web/JavaScript"}],
  links: [{"Wikipage": "https://en.wikipedia.org/wiki/JavaScript"}],
  icon: "https://cdn2.iconfinder.com/data/icons/nodejs-1/512/nodejs-512.png"
},
{
  id: 10,
  language: "C#",
  author: "Anders Hejlsberg (Microsoft)",
  description: "C# is a general-purpose, object-oriented programming language developed by Microsoft.",
  year: "2000",
  usedBy: "VisualStudio, Stack Overflow",
  usedFor: "Can be used with Microsofts .NET framework and is felxible enough to be used in most areas of software development",
  exampleCode: "public class Hello\n {\n    public static void Main()\n    {\n       System.Console.WriteLine('Hello, World!');\n    }\n  }",
  pros: ["Can be statically or dynamically typed", "Similiar syntax to other C languages", "Fully integrated with the .NET library."],
  cons: ["Less efficent as it is interpreted"],
  popularity: [
    {"2004": 4.9},
    {"2005": 5.6},
    {"2006": 6.2},
    {"2007": 6.3},
    {"2008": 7.3},
    {"2009": 6.0},
    {"2010": 5.8},
    {"2011": 5.6},
    {"2012": 8.8},
    {"2013": 9.0},
    {"2014": 8.9},
    {"2015": 8.8},
    {"2016": 8.5},
    {"2017": 8.1}
],
  documentation: [{"C# Docs": "https://docs.microsoft.com/en-us/dotnet/csharp/"}],
  links: [{"C# Tutorial": "http://csharp.net-tutorials.com/"}],
  icon: "http://devstickers.com/assets/img/pro/2p4i.png"
},
{
  id: 11,
  language: "TypeScript",
  author: "Microsoft/developed also by Anders Heilsberg",
  description: "TypeScript is a free and open-source programming language developed and maintaned by Microsoft",
  year: "2012",
  usedBy: "Microsoft",
  usedFor: "TypeScript originated from the perceived shortcomings of Javascript for the development of large-scale applications",
  exampleCode: "greet:('hello, world')",
  pros: ["Rich IDE support with autocomplete and code navgation features", "Typos caught at compilation time", "Class-based OO, with inheritance, private members and interfaces", "Any JavaScript code is a valid TypeScript code"],
  cons: ["In order to get the most out of TypeScript, developers will need to use the type annotations everywhere in their code, which might at times be cumbersome (or perceived as such coming from a dynamic lanuage background). Some effort might be required to write a stringly-typed version of the JavaScript code."],
  popularity: [
    {"2004": null},
    {"2005": null},
    {"2006": null},
    {"2007": null},
    {"2008": null},
    {"2009": null},
    {"2010": null},
    {"2011": null},
    {"2012": null},
    {"2013": null},
    {"2014": null},
    {"2015": null},
    {"2016": 1.1},
    {"2017": 1.4}
  ],
  documentation: [{"TypeScript Docs": "https://www.typescriptlang.org/docs/home.html"}],
  links: [{"YouTube Tutorial": "https://www.youtube.com/watch?v=xqYD8QXJX9U"}],
  icon: "http://www.typescriptlang.org/assets/images/icons/apple-touch-icon-180x180.png"

},
{
  id: 12,
  language: "Swift",
  author: "Chris Lattner and Apple Inc.",
  description: "Swift is a general-purpose, multi-paradigm, compiled programming language developed by Apple Inc. for iOS, macOS, watchOS, tvOS, and Linux. Swift is designed to work with Apple's Cocoa and Cocoa Touch frameworks and the large body of existing Objective-C (ObjC) code written for Apple products. Initially a proprietary language, version 2.2 was made open-source software under the Apache License 2.0 on December 3, 2015, for Apple's platforms and Linux.",
  year: "2014",
  usedBy: "Apple",
  usedFor: "iOS apps",
  exampleCode: "print('Hello, World!')",
  pros: ["If you know Objective C, it should be easier to pick up", "Can build iOS apps","Swift has a 'playground' that allows programmers to instantly see the result of code", "Open Source","Easier to learn than many other languages"],
  cons: ["Still in it's infancy so still has many issues that need to be addressed","Few IDEs available","Lack of support for apps less that iOS7"],
  popularity: [
    {"2004": null},
    {"2005": null},
    {"2006": null},
    {"2007": null},
    {"2008": null},
    {"2009": null},
    {"2010": null},
    {"2011": null},
    {"2012": null},
    {"2013": null},
    {"2014": 2.3},
    {"2015": 2.9},
    {"2016": 3.0},
    {"2017": 2.9}
  ],
  documentation: [{"Swift Docs": "https://swift.org/documentation/"}, {"Apple Swift Docs": "https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/index.html#//apple_ref/doc/uid/TP40014097-CH3-ID0"}],
  links: [{"Swift Tutorial": "https://www.raywenderlich.com/143771/swift-tutorial-part-1-expressions-variables-constants"}, {"Swift tutorial list": "http://www.skilledup.com/articles/6-best-free-swift-tutorials-programming-new-language"}],
  icon: "https://developer.apple.com/swift/images/swift-og.png"
}
];

//insert 
db.languages.insert(languageData);